ifeq ($(OMBUILDDIR),)
$(error OMBUILDDIR variable is not set.)
endif

all: install

install:
	mkdir -p $(OMBUILDDIR)/share/OMSens
	cp -rfp omsens $(OMBUILDDIR)/share/OMSens

clean:
	rm -rf $(OMBUILDDIR)/share/OMSens
